### ISSUE TITLE
[Rust] Vendored LLVM?

### ISSUE THREAD

**Issue by Etto48** [emproof-com/nyxstone#60]
Would it be possible to add a feature to the rust bindings to include a vendored version of LLVM?
This would avoid the need to have my own version of LLVM installed an make the installation process of any program that depends on this library easier.

**Comment by MolotovCherry** [comment]
I second this. This would - for most people - make using the crate almost completely painless.

**Comment by mrphrazer** [comment]
Hi! Based on our current schedule, we probably don't implement this on our own within the near future. However, please feel free to add this feature and make a PR.

**Comment by Etto48** [comment]
I'm trying to write a crate to compile llvm and integrate it as a feature of the rust bindings, I will do a PR if it works. I'm a bit concerned about compilation time because for what I tested (x86_64-pc-windows-msvc) it's really slow.

**Comment by Etto48** [comment]
I wrote a crate that compiles llvm but I have a lot of problems when I try to link the libraries that `llvm-config --system-libs --link-static` gives me. On linux some of them are not found, on windows they have conflicting symbols... I'm pretty much stuck at this point. Any help is welcome.

Here is a extract from the error log (on ubuntu)
```log
...
error: could not find native static library `rt`, perhaps an -L flag is missing?
error: linking with `cc` failed: exit status: 1
...
/usr/bin/ld: (.text+0x446): undefined reference to `_dl_x86_cpu_features'
...
/usr/bin/ld: (.text+0x5f6): undefined reference to `__scalbnf128'
...
/usr/bin/ld: (.text+0x123e): undefined reference to `__scalbn'
...
= note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
= note: use the `-l` flag to specify native libraries to link
...
```

**Comment by stuxnot** [comment]
First of all thank you for working on this!

I think long compilation times are to be expected with LLVM, maybe the crate (or nyxstone at a later point in time) could warn about the build time. There may be options to improve the time by configuring some LLVM cmake flags. See [tool/install-llvm.sh](https://github.com/emproof-com/nyxstone/blob/main/tool/install-llvm.sh) for some flags that I've found useful in the past and that improve the build time, tho I have to admit I'm not sure about all of these.

I've tried to build the crate on linux and noticed that it tries to install all LLVM tools, which is not really necessary, this should also be fixed via setting the LLVM build flags. The build also gets really large, so large in fact that I ran out of disk space and could not finish the build. Since I was able to build the LLVM libs previously on this machine, I assume that this is also related to the build configuration. 

Your issues regarding the libraries might also stem from the build config, since if I remember correctly there are some libraries LLVM will want to link against (if configured to) but not report this. The llvm-sys crate has a work-around to force linking against libffi because of this issue. Shoot me another message if there are more issues with linux.

**Comment by stuxnot** [comment]
Just wanted to let you know that it is quite likely that we will move to LLVM 18 soon, see #55. Since we will also support dynamic linking with the upgrade, having a vendored LLVM should be unnecessary for the time being. If you 'd like to continue to work on this or feel like it might still be useful, I'm still open to supporting vendored LLVM (18) for systems where there is no other way to get LLVM. Feel free to re-open this issue if this is the case.

Thanks again for putting in the work!
