### ISSUE TITLE
Update LLVM version

### ISSUE THREAD

**Issue by jonpalmisc** [emproof-com/nyxstone#66]
I noticed the LLVM version is currently [pinned to 15](https://github.com/emproof-com/nyxstone/blob/e1e258cbed6116964929dd9b3bd3f2ec9929d897/CMakeLists.txt#L28). At least on macOS, removing this and letting it use the LLVM 18 copy I have installed from Homebrew worked just fine.

Is there a more subtle reason for this requirement or can it be changed to allow newer versions as well?

**Comment by jonpalmisc** [comment]
Made an initial draft PR (#67) with the changes needed for building on macOS.

**Comment by stuxnot** [comment]
The reason we pinned the LLVM version is that Nyxstone is wrapping some MC classes to enable extracting additional info and implementing `adrp` relocations. Since the MC interface changed between versions, switching to 16 required additional work. We decided to keep it at 15, since it was working for us.

I've just checked out your PR and tested it (a bit), and adopted #55 to support LLVM version 18 and have not yet found any regressions. Really great find if this turns out to work consistently, since with support for the newest major version, building nyxstone should be a breeze for linux and windows. I'll have to investigate further to make sure llvm 18 is fully compatible and if any code changes will be necessary.

If everything checks out, I'm tempted to merge your PR into #55 and add support for dynamic linking together with version 18, since a blocker for dynamic linking was mainly that it didn't make a lot of sense without supporting the newest major version. @pkoppe and @g0ldminer, what do you guys think?

**Comment by jonpalmisc** [comment]
Please note the "notable TODOs" on the PR as I don't imagine it is merge-ready and has only been tested on macOS.

That said, that's good news, and let me know if I can be of any help.

**Comment by g0ldminer** [comment]
> If everything checks out, I'm tempted to merge your PR into #55 and add support for dynamic linking together with version 18, since a blocker for dynamic linking was mainly that it didn't make a lot of sense without supporting the newest major version. @pkoppe and @g0ldminer, what do you guys think?

Once all platforms have been tested and a clean llvm-latest (18) version is installed on the system with no traces of other LLVM versions, we should be confident to merge @jonpalmisc 's PR.
